DC-3152: Add API for read receipts on secure-message service
hmrc/secure-message pull request #32
Opened 2021-02-18 14:25 UTC by matthewgroom

2021-02-18 18:37 UTC, rwalpole requested changes

2021-02-18 18:37 UTC, rwalpole commented on conf/app.routes
> +POST        /conversation/add-read-time/:client/:conversationId                       uk.gov.hmrc.securemessage.controllers.SecureMessageController.addCustomerReadTime(client: String, conversationId:
This should be` POST /conversation/{client}/{conversation-id}/read-time `

2021-02-18 18:37 UTC, rwalpole commented on conf/application.conf
> +play.http.router = testOnlyDoNotUseInAppConf.Routes
Remove this.

2021-02-20 18:44 UTC, rwalpole requested changes

2021-02-20 18:44 UTC, rwalpole commented on test/resources/model/api/conversation-metadata.json
> +  "senderName": "Ben Dover",
This name doesn't seem appropriate for test data in a public HMRC GitHub repository.

2021-02-22 12:49 UTC, rwalpole approved these changes

2021-02-22 12:50 UTC, elabeca approved these changes

2021-02-22 13:12 UTC, merged