DC-2826: Create CDS conversation API
hmrc/secure-message pull request #4
Opened 2020-12-03 10:23 UTC by matthewgroom

2020-12-04 11:21 UTC, OlegEfrem approved these changes

2020-12-08 11:14 UTC, OlegEfrem requested changes

2020-12-08 11:14 UTC, OlegEfrem commented on it/CreateConversationISpec.scala
> +    "return BAD REQUEST when sent a minimal and valid JSON payload" in {
did you want to say invalid payload ?

2020-12-08 11:14 UTC, OlegEfrem commented on test/uk/gov/hmrc/securemessage/controllers/SecureMessageControllerSpec.scala
> +  private def getFullConversationJson = Json.parse("""
these should go to json files in resources directory

2020-12-10 16:50 UTC, lxol approved these changes

2020-12-10 16:52 UTC, elabeca approved these changes

2020-12-10 16:56 UTC, OlegEfrem approved these changes

2020-12-10 17:04 UTC, merged

2020-12-10 17:06 UTC, elabeca commented
I forgot to ask why the resource files in integration tests were kebab case and in unit tests they were pascal cased?